version: '3.6'

services:
    splunk:
        image: "splunk/splunk:latest"
        container_name: splunk-app-examples
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_PASSWORD=changed!
        ports:
            - 8000:8000
            - 8088:8088
            - 8089:8089
        volumes:
            - ./case_studies/weather_app_example:/opt/splunk/etc/apps/weather_app_example
            - ./case_studies/weather_dependent_app_example:/opt/splunk/etc/apps/weather_dependent_app_example
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000']
            interval: 5s
            timeout: 5s
            retries: 20
